### ISSUE TITLE
Search suggestions should be actionable

### ISSUE THREAD

**Issue by nlefler** [Maybulb/Nimble#20]
A feature request:

Nimble suggests some interesting searches, e.g. "What's the speed of an unladen swallow?". Pressing the search icon should act on the suggestion. Instead an error is displayed.

Prompt: "What's the speed of an unladen swallow?"
Expected: Pressing search icon searches for the prompt
Actual: "Error: Use your words"

**Comment by jmshal** [comment]
Hey @nlefler, great news. I know that we've discussed this exact feature pretty recently. So I would expect it in the not-so-distant future 👍

**Comment by ethel-dev** [comment]
Just got added in v1.2.1
