### ISSUE TITLE
"The application "Nimble.app" can't be opened."

### ISSUE THREAD

**Issue by jmshal** [Maybulb/Nimble#23]
rxcs (Christopher Sardegna) from Twitter is reporting the app cannot be opened.

OS: Mac OS X El Capitan
Nimble version: 1.3.2
Downloaded from: https://github.com/Maybulb/Nimble/releases/download/1.3.2/Nimble-1.3.2.dmg

I'm running exactly the same OS & version of Nimble, but I have our code signing certs installed, so it's not exactly a fair test. Could we use our testing machines to see whether this can be replicated?

**Comment by jmshal** [comment]
Update: User is reporting the issue has only started occurring since 1.3.0. Potentially meaning it's related to the fact we started code signing the app since then.

**Comment by jmshal** [comment]
Update: I don't think this issue has anything to do with code signing. User has reported that even when specifying all applications have the ability to run the error still occurs.

Full conversation thread: https://twitter.com/heyimjacooob/status/756728971782270976

**Comment by jmshal** [comment]
Here's all the facts so far.
- Checksum matched that of the DMG I downloaded myself, from the same location
- System Security & Privacy settings are correct (not set to "App Store only")
- Operating system is up to date & matches that of all our development environments
- Using the latest version of Nimble

**Comment by jmshal** [comment]
Screenshot from the user's logs.

![https://pbs.twimg.com/media/CoByZwQUsAA_tKS.jpg](https://pbs.twimg.com/media/CoByZwQUsAA_tKS.jpg)

**Comment by ReagentX** [comment]
[Archive](http://www.exquisitetweets.com/tweets?eids=33Tdvvvqov.33UdeK4lau.33U2IezAXc.33VD8heSxU.33VQ630Px7.33WtJHvlu0.33Wx4X1JQK.33WzkP4Ktg.33WYlqs0tj.33WZpyq7e8.33W2AvdrUG.33W5SEdt6G.33W7UoejPU.33XkuiPVoP.33Xm31BDI4.33YJhG345U.33YN1YP9Hw.33YRsMjoaX.33Y1x4maku.33Y5qXgYHF.33ZamTax5g.33ZlnZpWma.33Zp4s1DhI.33ZRsyAsmG.33ZW08t7K0.330eq9DwxV.330kXVC1BY.330pvcpE0O.331nSvfQuA.331rqwmRs5.331F4MMKei.331JvQrqiy.332eFhYNj2.332puV1SpM.332tQF4mzs.332OvWxE1k.3327gORAom.333IzanYpE.3339GGoAvY.334eSbF5VI.334sOlau76.337Ea52jPo.3381cfnjPg.3385eYhF5o.339qVg7I3a.34aikxDixg.34atXudsTl.34aINdoCaW) of the Tweets in question. I was able to solve the problem by first opening Nimble on the disk image, quitting, then copying to /Applications.

**Comment by jmshal** [comment]
Cheers, @ReagentX.
